[server]
headless = true
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1D4ED8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#172033"
font = "sans serif"
